// AUTO-GENERATED by scripts/extract-i18n.mjs — do not edit by hand.
// Language list and translations are derived from the upstream Rnote PO files.
export interface LanguageOption {
  code: string
  nativeName: string
  englishName: string
  rtl?: boolean
  /** number of translated strings available in the bundle */
  count: number
}

export const languages: LanguageOption[] = [
  { code: 'en', nativeName: "English", englishName: "English", count: 659 },
  { code: 'ar', nativeName: "العربية", englishName: "Arabic", rtl: true, count: 519 },
  { code: 'eu', nativeName: "Euskara", englishName: "Basque", count: 0 },
  { code: 'bn', nativeName: "বাংলা", englishName: "Bengali", count: 551 },
  { code: 'bs', nativeName: "Bosanski", englishName: "Bosnian", count: 25 },
  { code: 'zh-CN', nativeName: "简体中文（中国）", englishName: "Chinese (China)", count: 659 },
  { code: 'zh-HK', nativeName: "繁體中文（香港）", englishName: "Chinese (Hong Kong)", count: 585 },
  { code: 'zh-Hans', nativeName: "简体中文", englishName: "Chinese (Simplified)", count: 585 },
  { code: 'zh-SG', nativeName: "简体中文（新加坡）", englishName: "Chinese (Singapore)", count: 585 },
  { code: 'zh-TW', nativeName: "繁體中文（台灣）", englishName: "Chinese (Taiwan)", count: 585 },
  { code: 'zh-Hant', nativeName: "繁體中文", englishName: "Chinese (Traditional)", count: 585 },
  { code: 'cs', nativeName: "Čeština", englishName: "Czech", count: 585 },
  { code: 'nl', nativeName: "Nederlands", englishName: "Dutch", count: 565 },
  { code: 'eo', nativeName: "Esperanto", englishName: "Esperanto", count: 121 },
  { code: 'fi', nativeName: "Suomi", englishName: "Finnish", count: 525 },
  { code: 'fr', nativeName: "Français", englishName: "French", count: 564 },
  { code: 'ka', nativeName: "ქართული", englishName: "Georgian", count: 239 },
  { code: 'de', nativeName: "Deutsch", englishName: "German", count: 585 },
  { code: 'he', nativeName: "עברית", englishName: "Hebrew", rtl: true, count: 585 },
  { code: 'hi', nativeName: "हिन्दी", englishName: "Hindi", count: 583 },
  { code: 'hu', nativeName: "Magyar", englishName: "Hungarian", count: 585 },
  { code: 'id', nativeName: "Bahasa Indonesia", englishName: "Indonesian", count: 582 },
  { code: 'ia', nativeName: "Interlingua", englishName: "Interlingua", count: 0 },
  { code: 'it', nativeName: "Italiano", englishName: "Italian", count: 585 },
  { code: 'ja', nativeName: "日本語", englishName: "Japanese", count: 503 },
  { code: 'ko', nativeName: "한국어", englishName: "Korean", count: 380 },
  { code: 'mk', nativeName: "Македонски", englishName: "Macedonian", count: 134 },
  { code: 'ms', nativeName: "Bahasa Melayu", englishName: "Malay", count: 4 },
  { code: 'ml', nativeName: "മലയാളം", englishName: "Malayalam", count: 74 },
  { code: 'enm', nativeName: "Middle English", englishName: "Middle English", count: 0 },
  { code: 'ne', nativeName: "नेपाली", englishName: "Nepali", count: 542 },
  { code: 'nb-NO', nativeName: "Norsk Bokmål", englishName: "Norwegian Bokmål", count: 42 },
  { code: 'fa', nativeName: "فارسی", englishName: "Persian", rtl: true, count: 226 },
  { code: 'pl', nativeName: "Polski", englishName: "Polish", count: 566 },
  { code: 'pt', nativeName: "Português", englishName: "Portuguese", count: 565 },
  { code: 'pt-BR', nativeName: "Português (Brasil)", englishName: "Portuguese (Brazil)", count: 583 },
  { code: 'ro', nativeName: "Română", englishName: "Romanian", count: 78 },
  { code: 'ru', nativeName: "Русский", englishName: "Russian", count: 565 },
  { code: 'sl', nativeName: "Slovenščina", englishName: "Slovenian", count: 8 },
  { code: 'es', nativeName: "Español", englishName: "Spanish", count: 585 },
  { code: 'sv', nativeName: "Svenska", englishName: "Swedish", count: 141 },
  { code: 'ta', nativeName: "தமிழ்", englishName: "Tamil", count: 565 },
  { code: 'th', nativeName: "ไทย", englishName: "Thai", count: 506 },
  { code: 'tr', nativeName: "Türkçe", englishName: "Turkish", count: 549 },
  { code: 'uk', nativeName: "Українська", englishName: "Ukrainian", count: 585 },
  { code: 'vi', nativeName: "Tiếng Việt", englishName: "Vietnamese", count: 47 }
]

export function isRtl(code: string): boolean {
  return languages.some((l) => l.code === code && l.rtl)
}

export function findLanguage(code: string): LanguageOption | undefined {
  return languages.find((l) => l.code === code)
}
