// Determinism regression: verifies the PCG64 + rand_distr ports against vectors
// generated by rand_pcg 0.10.2 / rand 0.10 / rand_distr 0.6.0 (the versions in
// Rnote's Cargo.lock) with Pcg64::seed_from_u64(42).
import { Pcg64, seedAdvance } from '../src/compose/style/rand/pcg64'
import {
  standardF64,
  standardBool,
  open01F64,
  UniformF64,
  normalSample,
  exp1
} from '../src/compose/style/rand/distributions'
import { PenPath, Element as PenPathElement } from '../src/compose/penpath/penpath'
import { Vec2 } from '../src/compose/geometry/vec2'
import {
  TexturedOptions,
  TexturedDotsDistribution,
  TexturedShape,
  PressureCurve
} from '../src/compose/style/options'
import { Color } from '../src/compose/style/color'
import { generateTexturedDots } from '../src/compose/style/brush-render'

function approx(a: number, b: number, label: string) {
  if (Object.is(a, b)) return
  if (Math.abs(a - b) <= 1e-12 * Math.max(1, Math.abs(a), Math.abs(b))) return
  throw new Error(`${label}: got ${a}, expected ${b}`)
}

let r = new Pcg64(42n)
const u64 = [4178418447715145737n, 4410739922618931473n, 14034899209665866285n, 9736923071240364268n, 17902128262962705724n]
for (const expected of u64) {
  const got = r.nextU64()
  if (got !== expected) throw new Error(`u64: got ${got}, expected ${expected}`)
}

r = new Pcg64(42n)
const f64 = [0.2265125179283135, 0.23910669031859955, 0.760833410686741, 0.5278396573581516, 0.9704763177409157, 0.37546268141451944, 0.1879083014236631, 0.524657662927804]
f64.forEach((v) => approx(standardF64(r), v, 'f64'))

r = new Pcg64(42n)
const bools = [true, false, true, true, false, true, false, true, true, false, true, true]
for (const b of bools) {
  if (standardBool(r) !== b) throw new Error('bool mismatch')
}

r = new Pcg64(42n)
const ux = UniformF64.new(-123.456, 123.456)
;[-67.52734117328428, -64.41768888005399, 64.40289909948457, 6.873945477615948, 116.16624856604498].forEach((v) => approx(ux.sample(r), v, 'ux'))
const uy = UniformF64.new(-3, 3)
;[-0.7472239115128834, -1.8725501914580214, 0.14794597756682348, 1.8155315746506826, -0.77485843487344].forEach((v) => approx(uy.sample(r), v, 'uy'))
const ur = UniformF64.new(0.8 * 1.92, 1.25 * 1.92)
;[1.7402075046428793, 2.3383420127411245, 1.9357736189015087, 1.9163824447370905, 1.8060773643059953].forEach((v) => approx(ur.sample(r), v, 'ur'))

r = new Pcg64(42n)
;[-1.6050252119745185, -1.3986566738719157, 1.1598966197292604, 0.038294444954214774, 1.941907513133655, -0.33897796382328055, -0.5391668380647656, 0.036364490613223215]
  .forEach((v) => approx(normalSample(r, 0, 1), v, 'normal'))

r = new Pcg64(42n)
;[1.1736717307011344, 1.0533337602877233, 2.407317507981737, 0.23400602892558447, 2.6955039374996157, 0.5116191174775945, 0.12068522660259809, 0.2604337918671264]
  .forEach((v) => approx(exp1(r), v, 'exp'))

r = new Pcg64(42n)
;[0.2265125179283135, 0.23910669031859955, 0.760833410686741, 0.5278396573581516, 0.9704763177409157]
  .forEach((v) => approx(open01F64(r), v, 'open01'))

for (const [seed, expected] of [
  [0n, 2354861276966075475n],
  [1n, 15492934433077865799n],
  [2n, 1084574603684186893n],
  [42n, 4178418447715145737n],
  [123456789n, 13819137041856559632n]
] as const) {
  const got = seedAdvance(seed)
  if (got !== expected) throw new Error(`seedAdvance(${seed}): got ${got}, expected ${expected}`)
}

// Textured segment reference (replicates rnote-compose textured/mod.rs for a
// 100px horizontal segment, width 6, density 5, linear curve, seed 42).
function makeTexturedOptions(distribution: TexturedDotsDistribution): TexturedOptions {
  const o = new TexturedOptions()
  o.seed = 42
  o.stroke_width = 6
  o.density = 5
  o.distribution = distribution
  o.pressure_curve = PressureCurve.Linear
  o.shape = TexturedShape.Dots
  o.stroke_color = Color.BLACK
  return o
}
const texturedPath = new PenPath([
  new PenPathElement(new Vec2(0, 0), 0.3),
  new PenPathElement(new Vec2(100, 0), 0.7)
])
// (x, y, rotation, rx) for the first 8 stamps; x/rotation/rx are shared by all
// distributions because each distribution consumes exactly one draw for y.
const texturedExpected: Record<string, { y: number[]; rows: Array<[number, number, number]> }> = {
  uniform: {
    y: [-0.82046244621506, 1.411428953222747, 0.907765787325341, -0.111897156591984, 0.170317572287216, 1.488858635343712, -0.203604509487811, 0.870229298711473],
    rows: [
      [23.910669031859943, 0.204858081706059, 1.618543439465423],
      [37.546268141451947, -0.245116246873445, 1.616309679375318],
      [37.085692752109331, -0.207069221631024, 1.899902885352164],
      [44.025745918644745, -0.147191829498317, 1.310703326069182],
      [21.079648777222104, 0.203160466986435, 1.550496743053654],
      [27.935192266944252, -0.231952551397226, 1.250846733743392],
      [60.216449875759977, -0.020016919731352, 1.26739063221722],
      [48.222317467537493, 0.280315279063922, 1.898981723373911]
    ]
  },
  normal: {
    y: [2.407537817961778, 2.912861269700482, 0.988222331440037, 0.157526386290736, 0.492919671756575, 0.469496558977611, 0.136405431889646, 0.814258264444231],
    rows: [
      [23.910669031859943, 0.204858081706059, 1.618543439465423],
      [37.546268141451947, -0.245116246873445, 1.616309679375318],
      [37.085692752109331, -0.207069221631024, 1.899902885352164],
      [44.025745918644745, -0.147191829498317, 1.310703326069182],
      [21.079648777222104, 0.203160466986435, 1.550496743053654],
      [0.405517627263727, -0.053303535937055, 1.670719478127835],
      [2.76219832154132, 0.227825497647547, 1.586520668622113],
      [92.732439227052765, -0.325574653355434, 1.585537175996677]
    ]
  },
  exp: {
    y: [1.5, 1.5, 1.130713684340308, 1.001142824044228, 1.5, 0.089193029046791, 1.5, 0.670811603765719],
    rows: [
      [23.910669031859943, 0.204858081706059, 1.618543439465423],
      [37.546268141451947, -0.245116246873445, 1.616309679375318],
      [37.085692752109331, -0.207069221631024, 1.899902885352164],
      [44.025745918644745, -0.147191829498317, 1.310703326069182],
      [21.079648777222104, 0.203160466986435, 1.550496743053654],
      [0.405517627263727, -0.053303535937055, 1.670719478127835],
      [2.76219832154132, 0.227825497647547, 1.586520668622113],
      [92.732439227052765, -0.325574653355434, 1.585537175996677]
    ]
  },
  rexp: {
    y: [0, 0, 0.369286315659692, 0.498857175955772, 0, 1.410806970953209, 0, 0.829188396234281],
    rows: [
      [23.910669031859943, 0.204858081706059, 1.618543439465423],
      [37.546268141451947, -0.245116246873445, 1.616309679375318],
      [37.085692752109331, -0.207069221631024, 1.899902885352164],
      [44.025745918644745, -0.147191829498317, 1.310703326069182],
      [21.079648777222104, 0.203160466986435, 1.550496743053654],
      [0.405517627263727, -0.053303535937055, 1.670719478127835],
      [2.76219832154132, 0.227825497647547, 1.586520668622113],
      [92.732439227052765, -0.325574653355434, 1.585537175996677]
    ]
  }
}
const distributionMap: Record<string, TexturedDotsDistribution> = {
  uniform: TexturedDotsDistribution.Uniform,
  normal: TexturedDotsDistribution.Normal,
  exp: TexturedDotsDistribution.Exponential,
  rexp: TexturedDotsDistribution.ReverseExponential
}
for (const [name, expected] of Object.entries(texturedExpected)) {
  const dots = generateTexturedDots(texturedPath, makeTexturedOptions(distributionMap[name]))
  if (dots.length !== 150) throw new Error(`textured ${name}: ${dots.length} dots, expected 150`)
  for (let i = 0; i < 8; i++) {
    const d = dots[i]
    approx(d.x, expected.rows[i][0], `textured ${name}[${i}].x`)
    approx(d.y, expected.y[i], `textured ${name}[${i}].y`)
    approx(d.rot, expected.rows[i][1], `textured ${name}[${i}].rot`)
    approx(d.rx, expected.rows[i][2], `textured ${name}[${i}].rx`)
    if (d.ry !== d.rx) throw new Error(`textured ${name}[${i}]: circle ry must equal rx`)
  }
}

console.log('PASS PCG64 / rand_distr / textured reference vectors')
